#!/bin/sh

#自动语言
uci set luci.main.lang=auto
uci commit luci

#自动挂载
uci set fstab.@global[0].anon_mount=1
uci commit fstab

#Argon 主题
ln -sf /www/luci-static/argon/favicon.ico /www/favicon.ico
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci
uci set argon.@global[0].bing_background='1'
uci commit argon

#时区设置
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='cn.ntp.org.cn'
uci add_list system.ntp.server='ntp.ntsc.ac.cn'
uci commit system

#Dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

#PASSWALL
[ -f '/usr/share/v2ray/geoip.dat' ] && uci set passwall.@global_rules[0].v2ray_location_asset='/usr/share/v2ray/'
uci set passwall.@global_subscribe[0].ss_aead_type='shadowsocks-rust'
uci set passwall.@global_delay[0].start_delay='5'
uci set passwall.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall

#Feeds 更换镜像源
#sed -i 's,21.02,21.02-SNAPSHOT,g' /etc/opkg/distfeeds.conf
sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

#uhttpd 设置
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
#uci set uhttpd.main.tcp_keepalive=0
#uci set uhttpd.main.script_timeout=65535
#uci set uhttpd.main.script_network_timeout=65535
uci commit uhttpd
/etc/init.d/uhttpd restart

#nginx 设置
sed -i 's,deny all,allow all,g' /etc/nginx/restrict_locally
uci delete nginx._redirect2ssl.return
uci delete nginx._redirect2ssl.include
uci add_list nginx._redirect2ssl.include='restrict_locally'
uci add_list nginx._redirect2ssl.include='conf.d/*.locations'
uci commit nginx
/etc/init.d/nginx restart

#在防火墙默认开启全锥形 NAT 以及关闭 Flow Offloading
uci set firewall.@defaults[0].fullcone='2'
uci set firewall.@defaults[0].flow_offloading='1'
uci commit firewall

#默认开启 Packet Steering
uci set network.globals.packet_steering='1'
uci set network.lan.ip6assign='64'
uci commit network

#通用即插即用
uci set upnpd.config.enabled='1'
#uci del upnpd.config.use_stun
#uci del upnpd.config.stun_host
uci commit upnpd

#网易云音乐
#echo "59.111.239.62 httpdns.n.netease.com" >> /etc/hosts && cat /etc/hosts | sort | uniq > /tmp/tmp_hosts && cat /tmp/tmp_hosts > /etc/hosts
echo "10 2 * * * cd /usr/share/unblockneteasemusic/core/ && openssl req -new -x509 -key server.key -out server.crt -days 3650  -subj "/CN=*.music.163.com" && cd" >> /etc/crontabs/root && cat /etc/crontabs/root | sort -u > /tmp/tmp_cron_root && cat /tmp/tmp_cron_root > /etc/crontabs/root

#定时清理
(crontab -l | sed '/find \/tmp/d'; echo "0 0 1 * * find /tmp -type f \( -name \"*.log\" -o -name \"*.txt\" \) -exec sh -c 'rm {} && touch {}' \;") | sed '/^$/d' | crontab -

#rpcd
[ $(uci -q get rpcd.@rpcd[0].timeout) -lt 60 ] && uci set rpcd.@rpcd[0].timeout=60 && uci commit rpcd

#OpenClash 设置
echo "/etc/openclash/" >> /etc/sysupgrade.conf && cat /etc/sysupgrade.conf | sort | uniq > /tmp/tmp_sysupgrade_conf && cat /tmp/tmp_sysupgrade_conf > /etc/sysupgrade.conf

#Dockerman 设置
#sed -i 's,/opt,/overlay,g' /etc/config/dockerman

#qBittorrent 设置
#echo "nobody:x:65534:" >> /etc/group

#dnsmasq 设置以及开启 IPv6
#uci set dhcp.lan.ra='hybrid'
#uci set dhcp.lan.ndp='hybrid'
#uci set dhcp.lan.dhcpv6='hybrid'
#uci set dhcp.lan.ra_management='1'
uci del dhcp.lan.ra
uci del dhcp.lan.dhcpv6
uci del dhcp.lan.ndp
uci set dhcp.lan.ra_useleasetime='1'
uci set dhcp.lan.preferred_lifetime='8h'
uci del dhcp.@dnsmasq[0].rebind_protection
uci del dhcp.@dnsmasq[0].filteraaaa
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci commit dhcp
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

#计划任务
uci set system.@system[0].cronloglevel="9"
uci commit system
/etc/init.d/cron restart

#软链接
[ ! -f '/usr/bin/ip' ] && [ -f '/sbin/ip' ] && ln -sf /sbin/ip /usr/bin/ip
[ ! -f '/usr/bin/wget-ssl' ] && [ -f '/usr/bin/wget' ] && ln -sf /usr/bin/wget /usr/bin/wget-ssl
#[ ! -f '/usr/bin/ss-local' ] && [ -f '/usr/bin/sslocal' ] && ln -sf /usr/bin/sslocal /usr/bin/ss-local
[ ! -f '/usr/sbin/trojan' ] && [ -f '/usr/bin/trojan-go' ] && ln -sf /usr/bin/trojan-go /usr/bin/trojan
#[ ! -f '/usr/bin/v2ray' ] && [ -f '/usr/bin/xray' ] && ln -sf /usr/bin/xray /usr/bin/v2ray
#[ ! -f '/usr/bin/trojan-go' ] && [ -f '/usr/sbin/trojan-plus' ] && ln -sf /usr/sbin/trojan-plus /usr/bin/trojan-go

#Flag packages
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

#清理内存缓存
#sync; echo 3 > /proc/sys/vm/drop_caches

#自用
#[ -f '/rom/etc/rpcd_10_system.js' ] && rm -f /etc/rpcd_10_system.js
#[ -f '/rom/etc/rpcd_10_system.js' ] && rm -f /www/luci-static/resources/view/status/include/10_system.js
#[ -f '/rom/etc/rpcd_10_system.js' ] && cp -f /rom/etc/rpcd_10_system.js /www/luci-static/resources/view/status/include/10_system.js
#[ -f '/etc/fucked' ] && sed -i '/Source Code/d' /www/luci-static/resources/view/status/include/10_system.js
#[ -f '/rom/etc/rpcd_10_system.js' ] && touch /etc/fucked

#禁用Docker自动启动
uci set dockerd.globals.auto_start='0'
uci commit dockerd

#禁用wrtbwmon自动启动
uci del wrtbwmon.general.enabled
uci commit wrtbwmon

#禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/php7-fastcgi disable 2>/dev/null
/etc/init.d/php7-fastcgi stop
/etc/init.d/php7-fpm disable 2>/dev/null
/etc/init.d/php7-fpm stop
/etc/init.d/php8-fastcgi disable 2>/dev/null
/etc/init.d/php8-fastcgi stop
/etc/init.d/php8-fpm disable 2>/dev/null
/etc/init.d/php8-fpm stop
/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnbridge stop
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnserver stop
/etc/init.d/softethervpnclient disable 2>/dev/null
/etc/init.d/softethervpnclient stop
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/haproxy stop
/etc/init.d/kcptun disable 2>/dev/null
/etc/init.d/kcptun stop
/etc/init.d/socat disable 2>/dev/null
/etc/init.d/socat stop
/etc/init.d/fa-rk3399-pwmfan disable 2>/dev/null
/etc/init.d/fa-rk3399-pwmfan stop
/etc/init.d/fa-rk3328-pwmfan disable 2>/dev/null
/etc/init.d/fa-rk3328-pwmfan stop
/etc/init.d/ttyd disable 2>/dev/null
/etc/init.d/ttyd stop
/etc/init.d/shortcut-fe disable 2>/dev/null
/etc/init.d/shortcut-fe stop
/etc/init.d/qemu-ga disable 2>/dev/null
/etc/init.d/qemu-ga stop
#/etc/init.d/dnsproxy disable 2>/dev/null
#/etc/init.d/dnsproxy stop
#/etc/init.d/dockerd disable 2>/dev/null
#/etc/init.d/dockerd stop

chmod 0755 /etc/init.d/*

#清除 LuCI 残留缓存
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
