#!/bin/sh
# From QiuSimons

if [ -d "/overlay" ]; then
    OVERLAY_DIR="/overlay"
else
    OVERLAY_DIR="/rom/overlay"
fi

cd $OVERLAY_DIR
rm -rf `ls | egrep -v '(upper|.fs_state)'`
cd $OVERLAY_DIR/upper
rm -rf `ls | egrep -v '(etc|usr)'`
cd $OVERLAY_DIR/upper/usr
rm -rf `ls | egrep -v '(share)'`
cd $OVERLAY_DIR/upper/usr/share
rm -rf `ls | egrep -v '(unblockneteasemusic|passwall)'`
cd $OVERLAY_DIR/upper/etc
rm -rf `ls | egrep -v '(config|zerotier|daed|daed-next|smartdns|ssrplus|bench.log|shadow|openclash|fucked|autotimeset)'`
cd $OVERLAY_DIR/upper/etc/config
rm -rf `ls | egrep -v '(ap_modem|daed|daed-next|arpbind|autoreboot|ddns|firewall|jd-dailybonus|network|oled|openclash|passwall|serverchan|shadowsocksr|sqm|unblockneteasemusic|weburl|zerotier|vssr|zero|dhcp|mosdns|appfilter|fstab|watchcat)'`
sleep 5 && touch /etc/banner && reboot
