#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start() {
	echo 1 > /proc/sys/net/core/backlog_threaded

	for i in $(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' | xargs)
	do
		{
			ethtool -K "$i" rx-checksum on
			ethtool -K "$i" tx-checksum-ip-generic on || {
				ethtool -K "$i" tx-checksum-ipv4 on
				ethtool -K "$i" tx-checksum-ipv6 on
			}
			ethtool -K "$i" tx-scatter-gather on
			ethtool -K "$i" gso on
			ethtool -K "$i" tso on
			ethtool -K "$i" ufo on
		}
	done
} >"/dev/null" 2>&1
