name: Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    name: Build the APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Prepare
      run: |
        mkdir -p bin/luci-app-argon-config
        cp -rf ./htdocs ./po ./root ./Makefile ./bin/luci-app-argon-config
        echo "DIR=$(pwd)/bin/luci-app-argon-config"
    - name: Docker Build
      run: |
        docker pull openwrt/sdk
        docker run --rm -u root -v ${{ github.workspace }}/bin/:/builder/bin -v ${{ github.workspace }}/.github/workflows:/builder/workflows openwrt/sdk /bin/sh /builder/workflows/build.sh
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        assets=()
        for asset in ./bin/packages/x86_64/base/*argon-config*.apk; do
          assets+=("$asset")
        done
        tag_name=${GITHUB_REF#refs/tags/}
        gh release create "$tag_name" "${assets[@]}" --title "$tag_name" --notes "Release $tag_name"
    - name: Upload Log
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: buildlog
        path: bin/logs.tar.xz
