#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cpulimit
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=cpulimit configuration module
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+cpulimit

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature