name: Build packages

on:
  workflow_dispatch:
  push:
    branches:
      - kix

jobs:
  prepare:
    name: Prepare version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate version metadata
        id: meta
        run: |
          latest_commit=$(grep 'PKG_SOURCE_VERSION:=' ./dae/Makefile | cut -d '=' -f 2 | cut -c 1-7)
          echo "version=$latest_commit" >> "$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-22.04
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic    
          - i386_pentium4
          - x86_64
        sdk:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install clang-15 llvm-15

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.26
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-dae
          NO_REFRESH_CHECK: true
          V: s

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

  release:
    name: Publish release
    runs-on: ubuntu-latest
    needs: 
      - prepare
      - build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          path: release-assets

      - name: Consolidate and de-duplicate assets
        run: |
          mkdir -p release-dist
          find release-assets -type f -exec cp -v {} release-dist/ \;
          ls -lah release-dist

      - name: Create or update GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: dae_kix_${{ needs.prepare.outputs.version }}
          tag: dae_kix_${{ needs.prepare.outputs.version }}
          commit: kix
          token: ${{secrets.ACTIONS_DEPLOY_KEY}}
          artifacts: "release-dist/*.ipk"
          allowUpdates: true
          replacesArtifacts: true
