#!/bin/sh

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@firewall[1]
	add ucitrack firewall
	set ucitrack.@firewall[1].init=shortcut-fe
	commit ucitrack
EOF
}

exit 0
