#!/bin/sh /etc/rc.common

START=99

start() {
    echo 1 > /proc/sys/net/ipv4/conf/br-lan/proxy_arp

    echo 65535 > /proc/sys/net/core/somaxconn
    echo 16384 > /proc/sys/net/ipv4/tcp_max_syn_backlog
    echo 16384 > /proc/sys/net/core/netdev_max_backlog

    mem_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    if [ "$mem_kb" -ge 4194304 ]; then
        t_max=134217728; c_max=4194304
    elif [ "$mem_kb" -ge 1048576 ]; then
        t_max=67108864; c_max=4194304
    else
        t_max=33554432; c_max=2097152
    fi

    echo "$t_max" > /proc/sys/net/core/rmem_max
    echo "$t_max" > /proc/sys/net/core/wmem_max
    echo "4096 87380 $t_max" > /proc/sys/net/ipv4/tcp_rmem
    echo "4096 65536 $t_max" > /proc/sys/net/ipv4/tcp_wmem
    echo "$c_max" > /proc/sys/net/ipv4/tcp_collapse_max_bytes

    enable_offload() {
        ethtool -K "$1" "$2" on 2>/dev/null || :
    }

    for NIC_PATH in /sys/class/net/*; do
        NIC=$(basename "$NIC_PATH")

        [ -d "$NIC_PATH/device" ] || continue
        IF_TYPE=$(cat "$NIC_PATH/type" 2>/dev/null)
        [ "$IF_TYPE" != "1" ] && continue

        (
            enable_offload "$NIC" rx-checksum
            enable_offload "$NIC" tx-checksum-ip-generic || {
                enable_offload "$NIC" tx-checksum-ipv4
                enable_offload "$NIC" tx-checksum-ipv6
            }
            for f in tx-scatter-gather rx tx sg gso gro rx-gro-list tso ufo rxvlan txvlan; do
                enable_offload "$NIC" "$f"
            done
        ) &
    done
}
