# Copyright (C) 2021 QiuSimons
#
# This is free software, licensed under the GNU General Public License v3.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for dnsproxy
LUCI_DEPENDS:=+dnsproxy
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
