include $(TOPDIR)/rules.mk

PKG_VERSION:=20251216
PKG_RELEASE:=6
PKG_NAME:=luci-app-frps

LUCI_TITLE:=LuCI support for Frps
LUCI_DEPENDS:=+libc
LUCI_PKGARCH:=all

# 实测INSTALL_BIN和显式chmod都不能给脚本x权限，原因不明
define Package/$(PKG_NAME)/install
$(INSTALL_DIR) $(1)/usr/lib/lua
$(INSTALL_DIR) $(1)/usr/lib/lua/luci
$(INSTALL_DIR) $(1)/usr/lib/lua/luci/controller
$(INSTALL_DIR) $(1)/usr/lib/lua/luci/model
$(INSTALL_DIR) $(1)/usr/lib/lua/luci/model/cbi
$(INSTALL_DIR) $(1)/usr/lib/lua/luci/model/cbi/frps
$(INSTALL_DIR) $(1)/usr/lib/lua/luci/view
$(INSTALL_DIR) $(1)/usr/lib/lua/luci/view/frps
$(INSTALL_DIR) $(1)/etc/init.d
$(INSTALL_DIR) $(1)/etc/config
$(INSTALL_DIR) $(1)/etc/uci-defaults
$(INSTALL_DIR) $(1)/usr/share
$(INSTALL_DIR) $(1)/usr/share/rpcd	
$(INSTALL_DIR) $(1)/usr/share/rpcd/acl.d

$(INSTALL_DATA) ./luasrc/controller/*.lua $(1)/usr/lib/lua/luci/controller/
$(INSTALL_DATA) ./luasrc/model/cbi/frps/*.lua $(1)/usr/lib/lua/luci/model/cbi/frps/
$(INSTALL_DATA) ./luasrc/view/frps/* $(1)/usr/lib/lua/luci/view/frps/
$(INSTALL_BIN) 	./root/etc/init.d/frps $(1)/etc/init.d/frps
chmod 0755 $(1)/etc/init.d/frps
$(INSTALL_CONF) ./root/etc/config/frps $(1)/etc/config/frps
$(INSTALL_DATA) ./root/etc/uci-defaults/* $(1)/etc/uci-defaults/
$(INSTALL_DATA) ./root/usr/share/rpcd/acl.d/* $(1)/usr/share/rpcd/acl.d/
endef

# 安装前脚本，若存在同名配置文件，本配置文件会被重命名但旧配置文件可能不兼容，导致luci界面首页空白
define Package/$(PKG_NAME)/preinst
#!/bin/sh
if [ -f /etc/config/frps ] ; then
  uci show frps.main >/dev/null 2>&1 && exit 0
  echo "备份旧 uci 配置文件 /etc/config/frps 到 /etc/config/frps.old"
  /etc/init.d/frps stop 2>/dev/null
  mv -f /etc/config/frps /etc/config/frps.old
fi
exit 0
endef

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
