import { computed, ref } from 'vue'

const zh = {
  home: '首页', nodes: '节点', devices: '设备规则', advanced: '高级设置', diagnostics: '诊断', logs: '日志',
  running: '运行中', stopped: '已停止', refresh: '刷新', start: '启动', stop: '停止', restart: '重启', more: '更多',
  currentMode: '当前模式', currentSource: '当前节点', apply: '一键应用', applying: '正在应用', preview: '应用预览', confirmApply: '确认应用', cancel: '取消',
  recentState: '最近状态', noError: '最近没有错误', rollback: '上次应用已回滚', takeover: '当前路由由高级配置管理。继续会由模式配置接管 global、group、routing 和 dns。', acknowledge: '我已了解接管范围',
  sourceRequired: '先选择一个节点或订阅', source: '代理出口', addNode: '添加节点', addSubscription: '添加订阅', name: '名称', link: '链接', add: '添加', remove: '移除', emptyNodes: '还没有可用节点或订阅', subscriptionNodes: '订阅节点', refreshSubscription: '刷新订阅', runtimeWaiting: '正在拉取订阅节点', runtimeUnavailable: '服务运行后可查看订阅节点', runtimeApiDisabled: 'Clash API 未启用，订阅仍会自动拉取；启用后可查看运行时节点', unassignedNodes: '未归类运行时节点', chooseNode: '选择此节点', subscriptionSource: '订阅来源',
  deviceHint: '按源 IP、网段或 MAC 指定直连或代理。模式规则仍负责其他设备。', address: '地址', outbound: '出口', direct: '直连', proxy: '代理', saveRules: '应用设备规则', noRules: '尚未添加设备规则', type: '类型',
  checkLatency: '检测延迟', checkAllLatency: '检测全部', checkingLatency: '检测中', latencyFailed: '失败', latencyTarget: '延迟',
  connectivity: '连通性', connectivityHint: '分别检测阿里、Google、GitHub 和 YouTube；阿里直连，其余经 Honk 代理出口', testConnectivity: '测试连通性', testingConnectivity: '测试中', connectivityPassed: '全部正常', connectivityFailed: '检测失败', connectivityAliyun: '阿里连接', connectivityGoogle: 'Google 连接', connectivityGithub: 'GitHub 连接', connectivityYoutube: 'YouTube 连接', connectivityDirect: '直连 · HTTP HEAD', connectivityProxy: 'Honk 代理出口 · URLTest', loading: '加载中', proxyService: 'Honk',
  rawConfig: '完整配置', restoreDefault: '恢复默认配置', restoreDefaultConfirm: '恢复 Honk 默认配置？当前配置会先备份到 last-good。', defaultRestored: '已恢复默认配置', validate: '校验', valid: '配置有效', advancedWarning: '高级配置会直接替换完整 config.dae，并经过同一套校验、备份和回滚流程。', advancedTabs: '高级设置子页面', globalSettings: '全局设置', fullConfigPage: '完整配置', advancedTabDiscardConfirm: '完整配置有未保存修改，切换后将丢弃这些修改。继续？', clashApi: 'Clash API', clashApiEnabled: '已启用', clashApiDisabled: '未启用', enableClashApi: '开启 Clash API', disableClashApi: '关闭 Clash API', clashApiHint: '开启后可在节点页面查看运行时订阅节点并执行延迟检测。', clashApiEnableConfirm: '开启 Clash API 并重启服务？', clashApiDisableConfirm: '关闭 Clash API 并重启服务？', networkBinding: '网络接口绑定', networkBindingHint: '选择 Honk 使用的实际三层设备。自动推荐仅在候选明确时可用。', refreshDiscovery: '刷新检测', lanInterface: 'LAN 接口', wanInterface: 'WAN 接口', interfaceAuto: '请选择实际设备', interfaceCandidates: '可用候选', interfaceUnknown: '未发现可用设备', interfaceAmbiguous: '接口发现存在歧义，请手动选择不同的 LAN/WAN 设备。', interfaceUnavailable: '当前网络状态没有可用候选，请先检查网络接口。', interfaceApply: '应用接口设置', interfaceApplyConfirm: '应用接口和拨号模式并重启 Honk？', interfaceApplied: '接口和拨号模式已应用', interfaceCurrent: '当前', interfaceRecommended: '推荐', interfaceStatusUp: '在线', interfaceStatusDown: '离线', interfaceRoute: '默认路由', dialMode: '拨号模式', dialModeIp: 'ip：简单 IP 路由，不嗅探', dialModeDomain: 'domain：默认，嗅探并校验目的 IP', dialModePlus: 'domain+：DNS 不经过 Honk 时使用', dialModePlusPlus: 'domain++：强制嗅探并按 SNI/Host 重路由', dialModeHint: '拨号模式决定连接建立前的域名嗅探和目的 IP 校验策略。',
  serviceState: '服务状态', configState: '配置校验', geoState: 'Geo 数据', runtimeFiles: '运行文件', runtimeHealth: '运行环境诊断', runtimeFilesHint: '逐项检查 Honk 核心、配置、启动脚本和 Geo 锁文件。', runtimeCore: 'Honk 核心', runtimeTool: 'Honk 工具', runtimeInit: '启动脚本', runtimeConfig: '当前配置', runtimeDefaultConfig: '默认配置', runtimeBackup: '配置备份', runtimeLauncher: '核心启动器', runtimeInterfaceDiscovery: '接口检测器', runtimeQuickWorker: '事务恢复器', runtimeGeoLock: 'Geo 锁文件', healthy: '正常', attention: '需处理', bytes: '字节',
  geoManagement: 'Geo 数据管理', geoManagementHint: '地址可使用官方源、镜像或代理地址。下载后会校验文件格式、哈希和标签。', geosite: 'GeoSite', geoip: 'GeoIP', geositeUrl: 'GeoSite 下载地址', geoipUrl: 'GeoIP 下载地址', allowCustomGeo: '允许自定义 Geo 数据', saveGeoSettings: '保存 Geo 设置', saving: '保存中', downloadGeo: '下载此文件', downloadAllGeo: '下载全部 Geo', downloading: '下载中', geoDownloaded: 'Geo 数据已更新', geoDownloadedRestart: 'Geo 数据已更新，请重启 Honk', path: '路径', size: '大小', sha256: 'SHA-256', labels: '标签', geoSettingsSaved: 'Geo 设置已保存',
  logEmpty: '暂无日志', updated: '已更新', applySuccess: '配置已应用', operationFailed: '操作失败',
  chinaDirect: '国内直连', chinaDirectDesc: '中国流量直连，其他流量代理', gfw: 'GFW', gfwDesc: 'GFW 域名代理，其他流量直连', chinaProxy: '国内代理', chinaProxyDesc: '中国流量代理，其他流量直连', global: '全局模式', globalDesc: '非内网流量全部代理',
  routeImpact: '路由影响', dnsImpact: 'DNS 影响', changedLines: '行变更', configRevision: '配置版本', menu: '主导航', close: '关闭',
}

const en: Record<keyof typeof zh, string> = {
  home: 'Home', nodes: 'Nodes', devices: 'Device rules', advanced: 'Advanced', diagnostics: 'Diagnostics', logs: 'Logs',
  running: 'Running', stopped: 'Stopped', refresh: 'Refresh', start: 'Start', stop: 'Stop', restart: 'Restart', more: 'More',
  currentMode: 'Current mode', currentSource: 'Current source', apply: 'Apply', applying: 'Applying', preview: 'Apply preview', confirmApply: 'Confirm apply', cancel: 'Cancel',
  recentState: 'Recent state', noError: 'No recent errors', rollback: 'The previous apply was rolled back', takeover: 'Custom routing is active. Continuing lets mode management replace global, group, routing, and dns.', acknowledge: 'I understand the takeover scope',
  sourceRequired: 'Select a node or subscription first', source: 'Proxy source', addNode: 'Add node', addSubscription: 'Add subscription', name: 'Name', link: 'Link', add: 'Add', remove: 'Remove', emptyNodes: 'No nodes or subscriptions are available', subscriptionNodes: 'Subscription nodes', refreshSubscription: 'Refresh subscription', runtimeWaiting: 'Fetching subscription nodes', runtimeUnavailable: 'Start the service to view subscription nodes', runtimeApiDisabled: 'The Clash API is off. Subscriptions still refresh automatically; enable it to view runtime nodes.', unassignedNodes: 'Unassigned runtime nodes', chooseNode: 'Choose this node', subscriptionSource: 'Subscription source',
  deviceHint: 'Route a source IP, subnet, or MAC directly or through the proxy. The mode handles all other devices.', address: 'Address', outbound: 'Outbound', direct: 'Direct', proxy: 'Proxy', saveRules: 'Apply device rules', noRules: 'No device rules', type: 'Type',
  checkLatency: 'Check latency', checkAllLatency: 'Check all', checkingLatency: 'Checking', latencyFailed: 'Failed', latencyTarget: 'Latency',
  connectivity: 'Connectivity', connectivityHint: 'Probe Alibaba, Google, GitHub, and YouTube separately; Alibaba is direct and the others use the Honk proxy exit', testConnectivity: 'Test connectivity', testingConnectivity: 'Testing', connectivityPassed: 'All passed', connectivityFailed: 'Check failed', connectivityAliyun: 'Alibaba connection', connectivityGoogle: 'Google connection', connectivityGithub: 'GitHub connection', connectivityYoutube: 'YouTube connection', connectivityDirect: 'Direct · HTTP HEAD', connectivityProxy: 'Honk proxy exit · URLTest', loading: 'Loading', proxyService: 'Honk',
  rawConfig: 'Full configuration', restoreDefault: 'Restore defaults', restoreDefaultConfirm: 'Restore the Honk default configuration? The current configuration will be backed up first.', defaultRestored: 'Default configuration restored', validate: 'Validate', valid: 'Configuration is valid', advancedWarning: 'Advanced configuration replaces config.dae through the same validation, backup, and rollback transaction.', advancedTabs: 'Advanced settings pages', globalSettings: 'Global settings', fullConfigPage: 'Full configuration', advancedTabDiscardConfirm: 'The full configuration has unsaved changes. Switching pages will discard them. Continue?', clashApi: 'Clash API', clashApiEnabled: 'Enabled', clashApiDisabled: 'Disabled', enableClashApi: 'Enable Clash API', disableClashApi: 'Disable Clash API', clashApiHint: 'Enable it to view runtime subscription nodes and run latency checks on the Nodes page.', clashApiEnableConfirm: 'Enable Clash API and restart the service?', clashApiDisableConfirm: 'Disable Clash API and restart the service?', networkBinding: 'Network interface binding', networkBindingHint: 'Choose the actual layer-3 devices Honk should use. Recommendations are shown only when the candidates are unambiguous.', refreshDiscovery: 'Refresh discovery', lanInterface: 'LAN interface', wanInterface: 'WAN interface', interfaceAuto: 'Choose an actual device', interfaceCandidates: 'Available candidates', interfaceUnknown: 'No usable device found', interfaceAmbiguous: 'Interface discovery is ambiguous. Select different LAN and WAN devices.', interfaceUnavailable: 'No usable candidate is available in the current network state.', interfaceApply: 'Apply interface settings', interfaceApplyConfirm: 'Apply the interfaces and dial mode, then restart Honk?', interfaceApplied: 'Interfaces and dial mode applied', interfaceCurrent: 'Current', interfaceRecommended: 'Recommended', interfaceStatusUp: 'Up', interfaceStatusDown: 'Down', interfaceRoute: 'Default route', dialMode: 'Dial mode', dialModeIp: 'ip: simple IP routing without sniffing', dialModeDomain: 'domain: default, sniff and verify the destination IP', dialModePlus: 'domain+: use when DNS does not pass through Honk', dialModePlusPlus: 'domain++: force sniffing and reroute by SNI/Host', dialModeHint: 'Controls domain sniffing and destination-IP verification before dialing.',
  serviceState: 'Service', configState: 'Configuration', geoState: 'Geo data', runtimeFiles: 'Runtime files', runtimeHealth: 'Runtime health', runtimeFilesHint: 'Checks the Honk binaries, configuration, init scripts, and Geo lock file individually.', runtimeCore: 'Honk core', runtimeTool: 'Honk tool', runtimeInit: 'Init script', runtimeConfig: 'Active configuration', runtimeDefaultConfig: 'Default configuration', runtimeBackup: 'Configuration backup', runtimeLauncher: 'Core launcher', runtimeInterfaceDiscovery: 'Interface discovery', runtimeQuickWorker: 'Transaction recovery', runtimeGeoLock: 'Geo lock file', healthy: 'Healthy', attention: 'Attention', bytes: 'bytes',
  geoManagement: 'Geo data management', geoManagementHint: 'Use an official, mirror, or proxy URL. Downloads are checked for format, hash, and labels.', geosite: 'GeoSite', geoip: 'GeoIP', geositeUrl: 'GeoSite download URL', geoipUrl: 'GeoIP download URL', allowCustomGeo: 'Allow custom Geo data', saveGeoSettings: 'Save Geo settings', saving: 'Saving', downloadGeo: 'Download file', downloadAllGeo: 'Download all Geo', downloading: 'Downloading', geoDownloaded: 'Geo data updated', geoDownloadedRestart: 'Geo data updated; restart Honk', path: 'Path', size: 'Size', sha256: 'SHA-256', labels: 'Labels', geoSettingsSaved: 'Geo settings saved',
  logEmpty: 'No logs yet', updated: 'Updated', applySuccess: 'Configuration applied', operationFailed: 'Operation failed',
  chinaDirect: 'China direct', chinaDirectDesc: 'Route China directly and proxy other traffic', gfw: 'GFW', gfwDesc: 'Proxy GFW domains and route other traffic directly', chinaProxy: 'China proxy', chinaProxyDesc: 'Proxy China traffic and route other traffic directly', global: 'Global', globalDesc: 'Proxy all non-private traffic',
  routeImpact: 'Routing impact', dnsImpact: 'DNS impact', changedLines: 'Changed lines', configRevision: 'Revision', menu: 'Primary navigation', close: 'Close',
}

const initial = navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en'
export const locale = ref<'zh' | 'en'>(initial)
export const strings = computed(() => locale.value === 'zh' ? zh : en)
export function t(key: keyof typeof zh): string { return strings.value[key] }
