#!/bin/sh
set -eu

die() {
	printf 'localClash iStore 安装失败：%s\n' "$*" >&2
	exit 1
}

need_command() {
	command -v "$1" >/dev/null 2>&1 || die "缺少必要命令：$1"
}

script_dir="$(CDPATH= cd "$(dirname "$0")" && pwd)"
cd "$script_dir"

command -v id >/dev/null 2>&1 || die "缺少必要命令：id"
[ "$(id -u)" = 0 ] || die "必须以 root 身份安装。"

for command_name in opkg sha256sum tar uname cp mv chmod mkdir rm find dirname; do
	need_command "$command_name"
done

[ -f bundle.env ] || die "缺少 bundle.env。"
[ -f checksums.sha256 ] || die "缺少 checksums.sha256。"

sha256sum -c checksums.sha256 >/dev/null || die "bundle SHA-256 校验失败。"

# bundle.env is generated by the trusted build and contains only fixed literals.
# shellcheck disable=SC1091
. ./bundle.env

[ "${BUNDLE_SCHEMA_VERSION:-}" = 1 ] || die "bundle schema 不受支持。"
[ -n "${BUNDLE_ARCH:-}" ] || die "bundle 未声明目标架构。"
[ -n "${LUCI_IPK:-}" ] || die "bundle 未声明 LuCI IPK。"

case "$(uname -m)" in
	x86_64|amd64) router_arch=x86_64 ;;
	aarch64|arm64) router_arch=aarch64 ;;
	*) die "不支持的路由器架构：$(uname -m)" ;;
esac
[ "$router_arch" = "$BUNDLE_ARCH" ] || die "架构不匹配：本机为 $router_arch，安装包为 $BUNDLE_ARCH。"
[ -f "packages/$LUCI_IPK" ] || die "LuCI IPK 不存在：$LUCI_IPK"
[ -f bin/localclash ] || die "localClash Core 不存在。"
[ -f bin/dnsqualify ] || die "dnsqualify 不存在。"
[ -f assets/localclash-base-assets.tar.gz ] || die "基础文件包不存在。"

install_tmp="/tmp/localclash-istore-install.$$"
state_dir=/root/localclash
cleanup() {
	rm -rf "$install_tmp"
}
trap cleanup EXIT HUP INT TERM
mkdir -p "$install_tmp/assets"
tar -xzf assets/localclash-base-assets.tar.gz -C "$install_tmp/assets" || die "无法解压基础文件。"

for required_path in \
	policy-templates/localclash-default.json \
	.runtime/mihomo/Country.mmdb \
	.runtime/mihomo/geoip.dat \
	.runtime/mihomo/geosite.dat \
	.runtime/mihomo/ASN.mmdb; do
	[ -f "$install_tmp/assets/$required_path" ] || die "基础文件不完整：$required_path"
done
[ -d "$install_tmp/assets/rule-sources" ] || die "基础文件不完整：rule-sources"
rule_source_found=false
for rule_source in "$install_tmp/assets/rule-sources"/*.json; do
	if [ -f "$rule_source" ]; then
		rule_source_found=true
		break
	fi
done
[ "$rule_source_found" = true ] || die "基础文件不完整：rule-sources/*.json"

mkdir -p "$install_tmp/stage/usr/local/bin" "$install_tmp/stage/root/localclash/.runtime/mihomo"
cp bin/localclash "$install_tmp/stage/usr/local/bin/localclash"
cp bin/dnsqualify "$install_tmp/stage/usr/local/bin/dnsqualify"
chmod 755 "$install_tmp/stage/usr/local/bin/localclash" "$install_tmp/stage/usr/local/bin/dnsqualify"
cp -R "$install_tmp/assets/policy-templates" "$install_tmp/stage/root/localclash/"
cp -R "$install_tmp/assets/rule-sources" "$install_tmp/stage/root/localclash/"
for geo_file in Country.mmdb geoip.dat geosite.dat ASN.mmdb; do
	cp "$install_tmp/assets/.runtime/mihomo/$geo_file" "$install_tmp/stage/root/localclash/.runtime/mihomo/$geo_file"
done

opkg install "packages/$LUCI_IPK" || die "opkg 无法安装 LuCI IPK；不会联网下载替代包。"

mkdir -p /usr/local/bin "$state_dir/.runtime/mihomo"
for binary_name in localclash dnsqualify; do
	cp "$install_tmp/stage/usr/local/bin/$binary_name" "/usr/local/bin/$binary_name.new.$$"
	chmod 755 "/usr/local/bin/$binary_name.new.$$"
	mv "/usr/local/bin/$binary_name.new.$$" "/usr/local/bin/$binary_name" || die "无法安装 $binary_name。"
done

for asset_dir in policy-templates rule-sources; do
	if ! (
		cd "$install_tmp/stage/root/localclash"
		find "$asset_dir" -type f -print | while IFS= read -r relative_path; do
			destination="$state_dir/$relative_path"
			mkdir -p "$(dirname "$destination")" || exit 1
			cp "$relative_path" "$destination.new.$$" || exit 1
			mv "$destination.new.$$" "$destination" || exit 1
		done
	); then
		die "无法安装 $asset_dir。"
	fi
done

for geo_file in Country.mmdb geoip.dat geosite.dat ASN.mmdb; do
	cp "$install_tmp/stage/root/localclash/.runtime/mihomo/$geo_file" "$state_dir/.runtime/mihomo/$geo_file.new.$$"
	mv "$state_dir/.runtime/mihomo/$geo_file.new.$$" "$state_dir/.runtime/mihomo/$geo_file" || die "无法安装 $geo_file。"
done

printf 'localClash iStore 安装完成。LuCI=%s，Core=%s，架构=%s。\n' \
	"$LUCI_VERSION" "$CORE_VERSION" "$BUNDLE_ARCH"
printf '安装程序没有修改订阅、策略或网络接管状态。\n'
