include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Honk
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+honk +luci-base +luci-compat +curl

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
