include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Honk
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+honk +luci-base +curl +rpcd-mod-ucode +ucode-mod-fs +ucode-mod-uci +ucode-mod-ubus

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
