#!/bin/sh
[ "$ACTION" = ifup ] || [ "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate ] && [ -z "$IFUPDATE_ADDRESSES" ] && [ -z "$IFUPDATE_DATA" ] && exit 0
. /lib/functions/network.sh
network_flush_cache
network_find_wan6 NET_IF6
network_find_wan NET_IF
[ "$INTERFACE" != "$NET_IF6" ] && [ "$INTERFACE" != "$NET_IF" ] && exit 0
(
    LOCK_FILE="/tmp/lock/dae_hotplug_lock"
    if [ -f "$LOCK_FILE" ]; then
        exit 1
    else
        echo $$ > "$LOCK_FILE" 2>/dev/null
        trap 'rm -f "$LOCK_FILE"' EXIT
        sleep 60
        /etc/init.d/dae hot_reload 2>&1
    fi
) &
