#!/bin/sh /etc/rc.common
# Copyright (C) 2020 IrineSistiana

START=91
USE_PROCD=1

PROG=/usr/bin/dnsproxy
ipv6flag="--ipv6-disabled"
cacheflag="--cache --cache-min-ttl=3600"
fastestflag="--fastest-addr"

inital_conf()
{
	config_load "DNSProxy"
	config_get "enabled" "DNSProxy" "enabled" "0"
	config_get "fastest" "DNSProxy" "fastest" "1"
	config_get "cache" "DNSProxy" "cache" "1"
	config_get "oversea_port" "DNSProxy" "oversea_port" "5335"
	config_get "oversea_dns" "DNSProxy" "oversea_dns" "tls://8.8.4.4:853 tls://1.1.1.1:853"
	config_get "oversea_noipv6" "DNSProxy" "oversea_noipv6" "1"
	config_get "mainland_port" "DNSProxy" "mainland_port" "6050"
	config_get "mainland_dns" "DNSProxy" "mainland_dns" "119.29.29.29 223.5.5.5 180.76.76.76"
}

service_triggers()
{
    procd_add_reload_trigger "DNSProxy"
}

reload_service()
{
    stop
    sleep 2s
    echo "dnsproxy is restarted!"
    start
}

restart_others()
{
    /etc/init.d/network reload
    /etc/init.d/dnsmasq reload
    ps | grep ssrplus |grep -v grep
    if [ $? -eq 0 ];  then
      /etc/init.d/shadowsocksr restart
    fi
}

restore_setting()
{
    sed -i "/list server/d" /etc/config/dhcp
    sed -i "/dhcp_option/d" /etc/config/dhcp
    uci commit dhcp
    uci set shadowsocksr.@global[0].pdnsd_enable='1'
    uci set shadowsocksr.@global[0].tunnel_forward='8.8.4.4:53'
    uci commit shadowsocksr
    uci del network.lan.dns
    uci del network.wan.peerdns
    uci del network.wan.dns
    uci commit network
}

prepare_setting()
{
    sed -i "/list server/d" /etc/config/dhcp
    uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#'$mainland_port''
    uci set dhcp.@dnsmasq[0].rebind_protection='0'
    lanip="$(uci get network.lan.ipaddr)"
    sed -i "/dhcp_option/d" /etc/config/dhcp
    sed -i "/dhcpv6/a\\\tlist dhcp_option '6,$lanip'" /etc/config/dhcp
    uci commit dhcp
    uci set shadowsocksr.@global[0].dports='1'
    uci set shadowsocksr.@global[0].pdnsd_enable='0'
    uci del shadowsocksr.@global[0].tunnel_forward
    uci commit shadowsocksr
    sed -i "/list dns/d" /etc/config/network
    uci set network.wan.peerdns='0'
    uci add_list network.wan.dns='127.0.0.1'
    uci add_list network.lan.dns='127.0.0.1'
    uci commit network
}

start_node1()
{
    procd_open_instance OVERSEA
    procd_set_param command $PROG -l "127.0.0.1" -p $oversea_port -u "/var/run/dnsproxy/dnsproxy_oversea.conf" --all-servers $fastestflag $cacheflag $ipv6flag
    procd_set_param user root
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance OVERSEA
    echo "dnsproxy OVERSEA is started!"
}

start_node2()
{
    procd_open_instance MAINLAND
    procd_set_param command $PROG -l "127.0.0.1" -p $mainland_port -u "/var/run/dnsproxy/dnsproxy_mainland.conf" --all-servers $fastestflag $cacheflag
    procd_set_param user root
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance MAINLAND
    echo "dnsproxy MAINLAND is started!"
}


start_service()
{
    # Reading config
    inital_conf

    if [ "$enabled" -eq 0 ]; then
        firstblood=$(uci -q get DNSProxy.DNSProxy.not_first_start)
	[ "${firstblood}" = "0" ] && restore_setting
	[ "${firstblood}" = "0" ] && restart_others
        echo "dnsproxy has turned off"
        return 1
    fi
    
    uci set DNSProxy.DNSProxy.not_first_start='1'
    uci commit DNSProxy
    
    prepare_setting

    [ -d "/var/run/dnsproxy" ] || mkdir -p "/var/run/dnsproxy"
    echo -e "${oversea_dns// /\\n}" > "/var/run/dnsproxy/dnsproxy_oversea.conf"
    echo -e "${mainland_dns// /\\n}" > "/var/run/dnsproxy/dnsproxy_mainland.conf"
    if [ "${oversea_noipv6}" = "0" ];  then
        ipv6flag=""
    fi
    if [ "${cache}" = "0" ];  then
        cacheflag=""
    fi
    if [ "${fastest}" = "0" ];  then
        fastestflag=""
    fi

    start_node1
    start_node2

    restart_others

    echo "dnsproxy turn on"
    echo "enabled="$enabled""
}

stop_service()
{
    config_load "DNSProxy"
    local enabled

    config_get_bool enabled DNSProxy enabled 0
    killall -q dnsproxy
    rm -f /var/run/dnsproxy/*
    if [ "$enabled" -eq 0 ]; then
        restore_setting
        restart_others
    fi
    echo "dnsproxy turn off"
    echo "enabled="$enabled""
}
