#!/bin/sh /etc/rc.common
# Copyright (C) 2020 IrineSistiana

START=91
USE_PROCD=1

PROG=/usr/bin/dnsproxy
ipv6flag="--ipv6-disabled"
cacheflag="--cache --cache-min-ttl=3600"
fastestflag="--fastest-addr"

inital_conf()
{
	config_load "dnsproxy"
	config_get "enabled" "dnsproxy" "enabled" "0"
	config_get "fastest" "dnsproxy" "fastest" "1"
	config_get "cache" "dnsproxy" "cache" "1"
	config_get "oversea_port" "dnsproxy" "oversea_port" "6051"
	config_get "oversea_dns" "dnsproxy" "oversea_dns" "tls://8.8.4.4:853 tls://1.1.1.1:853"
	config_get "oversea_noipv6" "dnsproxy" "oversea_noipv6" "1"
	config_get "mainland_port" "dnsproxy" "mainland_port" "6050"
	config_get "mainland_dns" "dnsproxy" "mainland_dns" "119.29.29.29 223.5.5.5 180.76.76.76"
}

service_triggers()
{
    procd_add_reload_trigger "dnsproxy"
}

reload_service()
{
    stop
    sleep 2s
    echo "dnsproxy is restarted!"
    start
}

start_node1()
{
    procd_open_instance OVERSEA
    procd_set_param command $PROG -l "127.0.0.1" -p $oversea_port -u "/var/run/dnsproxy/dnsproxy_oversea.conf" --all-servers $fastestflag $cacheflag $ipv6flag
    procd_set_param user root
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance OVERSEA
    echo "dnsproxy OVERSEA is started!"
}

start_node2()
{
    procd_open_instance MAINLAND
    procd_set_param command $PROG -l "127.0.0.1" -p $mainland_port -u "/var/run/dnsproxy/dnsproxy_mainland.conf" --all-servers $fastestflag $cacheflag
    procd_set_param user root
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance MAINLAND
    echo "dnsproxy MAINLAND is started!"
}


start_service()
{
    # Reading config
    inital_conf

    if [ "${enabled}" = "0" ];  then
        return 0
    fi

    [ -d "/var/run/dnsproxy" ] || mkdir -p "/var/run/dnsproxy"
    echo -e "${oversea_dns// /\\n}" > "/var/run/dnsproxy/dnsproxy_oversea.conf"
    echo -e "${mainland_dns// /\\n}" > "/var/run/dnsproxy/dnsproxy_mainland.conf"
    if [ "${oversea_noipv6}" = "0" ];  then
        ipv6flag=""
    fi
    if [ "${cache}" = "0" ];  then
        cacheflag=""
    fi
    if [ "${fastest}" = "0" ];  then
        fastestflag=""
    fi

    start_node1
    start_node2

    echo "dnsproxy turn on"
    echo "enabled="$enabled""
}

stop_service()
{
    config_load "dnsproxy"
    local enabled

    config_get_bool enabled dnsproxy enabled 0
    killall -q dnsproxy
    rm -f /var/run/dnsproxy/*
    echo "dnsproxy turn off"
    echo "enabled="$enabled""
}
