#!/bin/sh /etc/rc.common
#
# Copyright (c) 2014-2015 The Linux Foundation. All rights reserved.
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
# OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

#SFE connection manager has a lower priority, it should be started after other connection manager
#to detect the existence of connection manager with higher priority
START=70

#load shortcut-fe and connection manager
load_sfe() {
	local kernel_version=$(uname -r)

	echo 1 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal

	[ "$1" = "shortcut-fe-cm" ] && module_path=shortcut_fe_cm
	[ "$1" = "fast-classifier" ] && module_path=fast_classifier

	[ -e "/lib/modules/$kernel_version/$1.ko" ] && {
		[ -d "/sys/module/$module_path" ] || insmod /lib/modules/$kernel_version/$1.ko
	}
	[ "$1" = "fast-classifier" ] && echo 4 > /sys/fast_classifier/offload_at_pkts
}

start() {
	[ "$(uci -q get firewall.@defaults[0].shortcut_fe)" != 1 ] && return 1
	module=$(uci -q get firewall.@defaults[0].shortcut_fe_module)
	[ ! -d "/sys/kernel/debug/ecm" ] && load_sfe $module
}

stop() {
	[ -d "/sys/module/fast_classifier" ] && rmmod fast_classifier
	[ -d "/sys/module/shortcut_fe_cm" ] && rmmod shortcut_fe_cm
	echo 0 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal
}
